[2023-01-22T01:48:12.120+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: debts_tracker_etl.validate_payment_data manual__2023-01-22T01:48:01.826886+00:00 [queued]>
[2023-01-22T01:48:12.132+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: debts_tracker_etl.validate_payment_data manual__2023-01-22T01:48:01.826886+00:00 [queued]>
[2023-01-22T01:48:12.132+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T01:48:12.133+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-01-22T01:48:12.134+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T01:48:12.147+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): validate_payment_data> on 2023-01-22 01:48:01.826886+00:00
[2023-01-22T01:48:12.154+0000] {standard_task_runner.py:55} INFO - Started process 17171 to run task
[2023-01-22T01:48:12.159+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'debts_tracker_etl', 'validate_payment_data', 'manual__2023-01-22T01:48:01.826886+00:00', '--job-id', '270', '--raw', '--subdir', 'DAGS_FOLDER/debts_tracker_etl.py', '--cfg-path', '/tmp/tmpe3cheeyc']
[2023-01-22T01:48:12.162+0000] {standard_task_runner.py:83} INFO - Job 270: Subtask validate_payment_data
[2023-01-22T01:48:12.243+0000] {task_command.py:388} INFO - Running <TaskInstance: debts_tracker_etl.validate_payment_data manual__2023-01-22T01:48:01.826886+00:00 [running]> on host 365d47c8e5b5
[2023-01-22T01:48:12.318+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Tony Stark, Peter Parker
AIRFLOW_CTX_DAG_ID=debts_tracker_etl
AIRFLOW_CTX_TASK_ID=validate_payment_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-22T01:48:01.826886+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-22T01:48:01.826886+00:00
[2023-01-22T01:48:12.333+0000] {debts_tracker_transformer.py:77} INFO - setting debts is_in_payment_plan flag for debt_id: 0
[2023-01-22T01:48:12.334+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/transformers/debts_tracker/debts_tracker_transformer.py", line 80, in validate_payment_data
    payments = cls.get_payments(payment_plan)
  File "/opt/airflow/plugins/transformers/debts_tracker/debts_tracker_transformer.py", line 29, in get_payments
    payments_records = cls.payments[payment_plan_id]
AttributeError: type object 'DebtsTrackerTransformers' has no attribute 'payments'
[2023-01-22T01:48:12.347+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=debts_tracker_etl, task_id=validate_payment_data, execution_date=20230122T014801, start_date=20230122T014812, end_date=20230122T014812
[2023-01-22T01:48:12.361+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 270 for task validate_payment_data (type object 'DebtsTrackerTransformers' has no attribute 'payments'; 17171)
[2023-01-22T01:48:12.412+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-22T01:48:12.431+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
