[2023-01-22T00:51:38.644+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: debts_tracker_etl.load_debts_data scheduled__2023-01-21T00:51:22.585012+00:00 [queued]>
[2023-01-22T00:51:38.655+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: debts_tracker_etl.load_debts_data scheduled__2023-01-21T00:51:22.585012+00:00 [queued]>
[2023-01-22T00:51:38.656+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T00:51:38.656+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-01-22T00:51:38.657+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T00:51:38.670+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): load_debts_data> on 2023-01-21 00:51:22.585012+00:00
[2023-01-22T00:51:38.678+0000] {standard_task_runner.py:55} INFO - Started process 13579 to run task
[2023-01-22T00:51:38.682+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'debts_tracker_etl', 'load_debts_data', 'scheduled__2023-01-21T00:51:22.585012+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/debts_tracker_etl.py', '--cfg-path', '/tmp/tmp4e6vm5py']
[2023-01-22T00:51:38.686+0000] {standard_task_runner.py:83} INFO - Job 252: Subtask load_debts_data
[2023-01-22T00:51:38.770+0000] {task_command.py:388} INFO - Running <TaskInstance: debts_tracker_etl.load_debts_data scheduled__2023-01-21T00:51:22.585012+00:00 [running]> on host 365d47c8e5b5
[2023-01-22T00:51:38.838+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Bruce Wayne
AIRFLOW_CTX_DAG_ID=debts_tracker_etl
AIRFLOW_CTX_TASK_ID=load_debts_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-21T00:51:22.585012+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-21T00:51:22.585012+00:00
[2023-01-22T00:51:38.840+0000] {debts_tracker_transformer.py:11} INFO - init loading debts
[2023-01-22T00:51:38.841+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/transformers/debts_tracker/debts_tracker_transformer.py", line 12, in load_debts
    debts = HttpServices.get_debts()
  File "/opt/airflow/plugins/services/http_services.py", line 46, in get_debts
    debts = cls.fetch_debts_from_api()
AttributeError: type object 'HttpServices' has no attribute 'fetch_debts_from_api'
[2023-01-22T00:51:38.853+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=debts_tracker_etl, task_id=load_debts_data, execution_date=20230121T005122, start_date=20230122T005138, end_date=20230122T005138
[2023-01-22T00:51:38.865+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 252 for task load_debts_data (type object 'HttpServices' has no attribute 'fetch_debts_from_api'; 13579)
[2023-01-22T00:51:38.895+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-22T00:51:38.923+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
