[2023-01-22T03:48:54.182+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: debts_tracker_etl.create_encrypt_file manual__2023-01-22T03:48:48.649764+00:00 [queued]>
[2023-01-22T03:48:54.193+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: debts_tracker_etl.create_encrypt_file manual__2023-01-22T03:48:48.649764+00:00 [queued]>
[2023-01-22T03:48:54.194+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T03:48:54.195+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-01-22T03:48:54.195+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T03:48:54.208+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): create_encrypt_file> on 2023-01-22 03:48:48.649764+00:00
[2023-01-22T03:48:54.214+0000] {standard_task_runner.py:55} INFO - Started process 1689 to run task
[2023-01-22T03:48:54.219+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'debts_tracker_etl', 'create_encrypt_file', 'manual__2023-01-22T03:48:48.649764+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/debts_tracker_etl.py', '--cfg-path', '/tmp/tmp5r4cjy65']
[2023-01-22T03:48:54.222+0000] {standard_task_runner.py:83} INFO - Job 36: Subtask create_encrypt_file
[2023-01-22T03:48:54.301+0000] {task_command.py:388} INFO - Running <TaskInstance: debts_tracker_etl.create_encrypt_file manual__2023-01-22T03:48:48.649764+00:00 [running]> on host 4b1c480b6ccb
[2023-01-22T03:48:54.377+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Tony Stark, Peter Parker
AIRFLOW_CTX_DAG_ID=debts_tracker_etl
AIRFLOW_CTX_TASK_ID=create_encrypt_file
AIRFLOW_CTX_EXECUTION_DATE=2023-01-22T03:48:48.649764+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-22T03:48:48.649764+00:00
[2023-01-22T03:48:54.378+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: encrypt_debts_data() missing 1 required positional argument: 'op_kwargs'
[2023-01-22T03:48:54.388+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=debts_tracker_etl, task_id=create_encrypt_file, execution_date=20230122T034848, start_date=20230122T034854, end_date=20230122T034854
[2023-01-22T03:48:54.400+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 36 for task create_encrypt_file (encrypt_debts_data() missing 1 required positional argument: 'op_kwargs'; 1689)
[2023-01-22T03:48:54.432+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-22T03:48:54.453+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
