[2023-01-22T01:52:30.875+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: debts_tracker_etl.validate_payment_data manual__2023-01-22T01:52:20.391619+00:00 [queued]>
[2023-01-22T01:52:30.887+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: debts_tracker_etl.validate_payment_data manual__2023-01-22T01:52:20.391619+00:00 [queued]>
[2023-01-22T01:52:30.888+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T01:52:30.889+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-01-22T01:52:30.890+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T01:52:30.903+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): validate_payment_data> on 2023-01-22 01:52:20.391619+00:00
[2023-01-22T01:52:30.910+0000] {standard_task_runner.py:55} INFO - Started process 17453 to run task
[2023-01-22T01:52:30.914+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'debts_tracker_etl', 'validate_payment_data', 'manual__2023-01-22T01:52:20.391619+00:00', '--job-id', '276', '--raw', '--subdir', 'DAGS_FOLDER/debts_tracker_etl.py', '--cfg-path', '/tmp/tmpgqweypnk']
[2023-01-22T01:52:30.918+0000] {standard_task_runner.py:83} INFO - Job 276: Subtask validate_payment_data
[2023-01-22T01:52:30.997+0000] {task_command.py:388} INFO - Running <TaskInstance: debts_tracker_etl.validate_payment_data manual__2023-01-22T01:52:20.391619+00:00 [running]> on host 365d47c8e5b5
[2023-01-22T01:52:31.068+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Tony Stark, Peter Parker
AIRFLOW_CTX_DAG_ID=debts_tracker_etl
AIRFLOW_CTX_TASK_ID=validate_payment_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-22T01:52:20.391619+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-22T01:52:20.391619+00:00
[2023-01-22T01:52:31.087+0000] {logging_mixin.py:137} INFO - ---------------1
[2023-01-22T01:52:31.088+0000] {logging_mixin.py:137} INFO - the paiytmen {'0': [{'amount': 51.25, 'date': '2020-09-29', 'payment_plan_id': 0}, {'amount': 51.25, 'date': '2020-10-29', 'payment_plan_id': 0}], '1': [{'amount': 25, 'date': '2020-08-08', 'payment_plan_id': 1}, {'amount': 25, 'date': '2020-08-08', 'payment_plan_id': 1}], '2': [{'amount': 4312.67, 'date': '2020-08-08', 'payment_plan_id': 2}], '3': [{'amount': 1230.085, 'date': '2020-08-01', 'payment_plan_id': 3}, {'amount': 1230.085, 'date': '2020-08-08', 'payment_plan_id': 3}, {'amount': 1230.085, 'date': '2020-08-15', 'payment_plan_id': 3}]}
[2023-01-22T01:52:31.090+0000] {debts_tracker_transformer.py:79} INFO - setting debts is_in_payment_plan flag for debt_id: 0
[2023-01-22T01:52:31.091+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/transformers/debts_tracker/debts_tracker_transformer.py", line 82, in validate_payment_data
    payments = cls.get_payments(payment_plan)
  File "/opt/airflow/plugins/transformers/debts_tracker/debts_tracker_transformer.py", line 29, in get_payments
    payments_records = cls.payments[payment_plan_id]
KeyError: 0
[2023-01-22T01:52:31.104+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=debts_tracker_etl, task_id=validate_payment_data, execution_date=20230122T015220, start_date=20230122T015230, end_date=20230122T015231
[2023-01-22T01:52:31.126+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 276 for task validate_payment_data (0; 17453)
[2023-01-22T01:52:31.175+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-22T01:52:31.199+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
