[2023-01-21T06:00:50.131+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: crypto_coins_etl.insert_coins manual__2023-01-21T06:00:44.385729+00:00 [queued]>
[2023-01-21T06:00:50.144+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: crypto_coins_etl.insert_coins manual__2023-01-21T06:00:44.385729+00:00 [queued]>
[2023-01-21T06:00:50.145+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T06:00:50.146+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-21T06:00:50.146+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T06:00:50.162+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): insert_coins> on 2023-01-21 06:00:44.385729+00:00
[2023-01-21T06:00:50.169+0000] {standard_task_runner.py:55} INFO - Started process 2621 to run task
[2023-01-21T06:00:50.174+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'crypto_coins_etl', 'insert_coins', 'manual__2023-01-21T06:00:44.385729+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/crypto_coins_etl.py', '--cfg-path', '/tmp/tmppkusl37o']
[2023-01-21T06:00:50.178+0000] {standard_task_runner.py:83} INFO - Job 61: Subtask insert_coins
[2023-01-21T06:00:50.257+0000] {task_command.py:388} INFO - Running <TaskInstance: crypto_coins_etl.insert_coins manual__2023-01-21T06:00:44.385729+00:00 [running]> on host ac5a85f5e1cc
[2023-01-21T06:00:50.329+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=crypto_coins_etl
AIRFLOW_CTX_TASK_ID=insert_coins
AIRFLOW_CTX_EXECUTION_DATE=2023-01-21T06:00:44.385729+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-21T06:00:44.385729+00:00
[2023-01-21T06:00:50.362+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column coins.id does not exist
LINE 1: SELECT coins.id AS coins_id, coins.name AS coins_name, coins...
               ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/transformers/crypto/crypto_transformer.py", line 24, in insert_coin_in_db
    Coin.create(coin)
  File "/opt/airflow/plugins/models/coin.py", line 28, in create
    coin_checker = cls.get_coin_by_symbol(coin_info['symbol'])
  File "/opt/airflow/plugins/models/coin.py", line 54, in get_coin_by_symbol
    return cls.query.filter(cls.symbol == symbol).first()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2824, in first
    return self.limit(1)._iter().first()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column coins.id does not exist
LINE 1: SELECT coins.id AS coins_id, coins.name AS coins_name, coins...
               ^

[SQL: SELECT coins.id AS coins_id, coins.name AS coins_name, coins.symbol AS coins_symbol, coins.current_price AS coins_current_price, coins.high_24h AS coins_high_24h, coins.low_24h AS coins_low_24h 
FROM coins 
WHERE coins.symbol = %(symbol_1)s 
 LIMIT %(param_1)s]
[parameters: {'symbol_1': 'btc', 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2023-01-21T06:00:50.380+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=crypto_coins_etl, task_id=insert_coins, execution_date=20230121T060044, start_date=20230121T060050, end_date=20230121T060050
[2023-01-21T06:00:50.404+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 61 for task insert_coins ((psycopg2.errors.UndefinedColumn) column coins.id does not exist
LINE 1: SELECT coins.id AS coins_id, coins.name AS coins_name, coins...
               ^

[SQL: SELECT coins.id AS coins_id, coins.name AS coins_name, coins.symbol AS coins_symbol, coins.current_price AS coins_current_price, coins.high_24h AS coins_high_24h, coins.low_24h AS coins_low_24h 
FROM coins 
WHERE coins.symbol = %(symbol_1)s 
 LIMIT %(param_1)s]
[parameters: {'symbol_1': 'btc', 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/14/f405); 2621)
[2023-01-21T06:00:50.428+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-21T06:00:50.448+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
