[2023-01-22T03:08:52.627+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: crypto_currency_etl.load_coins scheduled__2023-01-21T03:08:44.342232+00:00 [queued]>
[2023-01-22T03:08:52.639+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: crypto_currency_etl.load_coins scheduled__2023-01-21T03:08:44.342232+00:00 [queued]>
[2023-01-22T03:08:52.640+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T03:08:52.641+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-01-22T03:08:52.642+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T03:08:52.661+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): load_coins> on 2023-01-21 03:08:44.342232+00:00
[2023-01-22T03:08:52.667+0000] {standard_task_runner.py:55} INFO - Started process 227 to run task
[2023-01-22T03:08:52.672+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'crypto_currency_etl', 'load_coins', 'scheduled__2023-01-21T03:08:44.342232+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/crypto_currency_etl.py', '--cfg-path', '/tmp/tmph4hjr7kr']
[2023-01-22T03:08:52.678+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask load_coins
[2023-01-22T03:08:52.789+0000] {task_command.py:388} INFO - Running <TaskInstance: crypto_currency_etl.load_coins scheduled__2023-01-21T03:08:44.342232+00:00 [running]> on host b6a4483f6ab0
[2023-01-22T03:08:52.881+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Bruce Wayne, Jason Todd
AIRFLOW_CTX_DAG_ID=crypto_currency_etl
AIRFLOW_CTX_TASK_ID=load_coins
AIRFLOW_CTX_EXECUTION_DATE=2023-01-21T03:08:44.342232+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-21T03:08:44.342232+00:00
[2023-01-22T03:08:52.883+0000] {crypto_transformer.py:15} INFO - init loading coin
[2023-01-22T03:08:52.886+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/transformers/crypto/crypto_transformer.py", line 16, in load_coins
    coins = HttpServices.get_coins()
  File "/opt/airflow/plugins/services/http_services.py", line 14, in get_coins
    response = requests.get('{cls.coins_base_url}markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false')
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '{cls.coins_base_url}markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false': No scheme supplied. Perhaps you meant https://{cls.coins_base_url}markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false?
[2023-01-22T03:08:52.906+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto_currency_etl, task_id=load_coins, execution_date=20230121T030844, start_date=20230122T030852, end_date=20230122T030852
[2023-01-22T03:08:52.921+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 5 for task load_coins (Invalid URL '{cls.coins_base_url}markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false': No scheme supplied. Perhaps you meant https://{cls.coins_base_url}markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false?; 227)
[2023-01-22T03:08:52.966+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-22T03:08:53.006+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
