[2023-01-21T05:06:01.908+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: crypto_coins_etl.create_table manual__2023-01-21T05:05:59.415849+00:00 [queued]>
[2023-01-21T05:06:01.920+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: crypto_coins_etl.create_table manual__2023-01-21T05:05:59.415849+00:00 [queued]>
[2023-01-21T05:06:01.921+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T05:06:01.922+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-21T05:06:01.922+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T05:06:01.936+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): create_table> on 2023-01-21 05:05:59.415849+00:00
[2023-01-21T05:06:01.942+0000] {standard_task_runner.py:55} INFO - Started process 1281 to run task
[2023-01-21T05:06:01.946+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'crypto_coins_etl', 'create_table', 'manual__2023-01-21T05:05:59.415849+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/crypto_coins_etl.py', '--cfg-path', '/tmp/tmpb46fgtyg']
[2023-01-21T05:06:01.947+0000] {standard_task_runner.py:83} INFO - Job 41: Subtask create_table
[2023-01-21T05:06:02.023+0000] {task_command.py:388} INFO - Running <TaskInstance: crypto_coins_etl.create_table manual__2023-01-21T05:05:59.415849+00:00 [running]> on host 492086e6db69
[2023-01-21T05:06:02.147+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=crypto_coins_etl
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-01-21T05:05:59.415849+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-21T05:05:59.415849+00:00
[2023-01-21T05:06:02.149+0000] {sql.py:254} INFO - Executing:    CREATE TABLE IF NOT EXISTS users(             firstname TEXT NOT NULL,             lastname TEXT NOT NULL,             country TEXT NOT NULL,             username TEXT NOT NULL,             password TEXT NOT NULL,             Email TEXT NOT NULL         );
[2023-01-21T05:06:02.191+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 255, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 179, in get_db_hook
    return self._hook
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 141, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres` isn't defined
[2023-01-21T05:06:02.200+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=crypto_coins_etl, task_id=create_table, execution_date=20230121T050559, start_date=20230121T050601, end_date=20230121T050602
[2023-01-21T05:06:02.216+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 41 for task create_table (The conn_id `postgres` isn't defined; 1281)
[2023-01-21T05:06:02.240+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-21T05:06:02.261+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
