[2023-01-22T01:56:42.253+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: debts_tracker_etl.validate_payment_data manual__2023-01-22T01:56:31.645551+00:00 [queued]>
[2023-01-22T01:56:42.268+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: debts_tracker_etl.validate_payment_data manual__2023-01-22T01:56:31.645551+00:00 [queued]>
[2023-01-22T01:56:42.269+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T01:56:42.270+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-01-22T01:56:42.270+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T01:56:42.284+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): validate_payment_data> on 2023-01-22 01:56:31.645551+00:00
[2023-01-22T01:56:42.290+0000] {standard_task_runner.py:55} INFO - Started process 17740 to run task
[2023-01-22T01:56:42.295+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'debts_tracker_etl', 'validate_payment_data', 'manual__2023-01-22T01:56:31.645551+00:00', '--job-id', '285', '--raw', '--subdir', 'DAGS_FOLDER/debts_tracker_etl.py', '--cfg-path', '/tmp/tmpig52oh0_']
[2023-01-22T01:56:42.299+0000] {standard_task_runner.py:83} INFO - Job 285: Subtask validate_payment_data
[2023-01-22T01:56:42.376+0000] {task_command.py:388} INFO - Running <TaskInstance: debts_tracker_etl.validate_payment_data manual__2023-01-22T01:56:31.645551+00:00 [running]> on host 365d47c8e5b5
[2023-01-22T01:56:42.447+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Tony Stark, Peter Parker
AIRFLOW_CTX_DAG_ID=debts_tracker_etl
AIRFLOW_CTX_TASK_ID=validate_payment_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-22T01:56:31.645551+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-22T01:56:31.645551+00:00
[2023-01-22T01:56:42.461+0000] {logging_mixin.py:137} INFO - ---------------1
[2023-01-22T01:56:42.462+0000] {logging_mixin.py:137} INFO - the paiytmen {'0': [{'amount': 51.25, 'date': '2020-09-29', 'payment_plan_id': 0}, {'amount': 51.25, 'date': '2020-10-29', 'payment_plan_id': 0}], '1': [{'amount': 25, 'date': '2020-08-08', 'payment_plan_id': 1}, {'amount': 25, 'date': '2020-08-08', 'payment_plan_id': 1}], '2': [{'amount': 4312.67, 'date': '2020-08-08', 'payment_plan_id': 2}], '3': [{'amount': 1230.085, 'date': '2020-08-01', 'payment_plan_id': 3}, {'amount': 1230.085, 'date': '2020-08-08', 'payment_plan_id': 3}, {'amount': 1230.085, 'date': '2020-08-15', 'payment_plan_id': 3}]}
[2023-01-22T01:56:42.463+0000] {debts_tracker_transformer.py:79} INFO - setting debts is_in_payment_plan flag for debt_id: 0
[2023-01-22T01:56:42.464+0000] {debts_tracker_transformer.py:30} INFO - Getting payments info for payment_plan_id: 0
[2023-01-22T01:56:42.464+0000] {debts_tracker_transformer.py:53} INFO - calculating remaining amount for payment_plan_id: 0
[2023-01-22T01:56:42.465+0000] {debts_tracker_transformer.py:36} INFO - checking if payments are on time
[2023-01-22T01:56:42.466+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/transformers/debts_tracker/debts_tracker_transformer.py", line 89, in validate_payment_data
    is_payment_on_time = cls.check_if_payment_on_time(payments, payment_plan['installment_frequency'])
  File "/opt/airflow/plugins/transformers/debts_tracker/debts_tracker_transformer.py", line 41, in check_if_payment_on_time
    if diff.days != cls.payment_frecuency[installment_frequency]:
AttributeError: type object 'DebtsTrackerTransformers' has no attribute 'payment_frecuency'
[2023-01-22T01:56:42.477+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=debts_tracker_etl, task_id=validate_payment_data, execution_date=20230122T015631, start_date=20230122T015642, end_date=20230122T015642
[2023-01-22T01:56:42.489+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 285 for task validate_payment_data (type object 'DebtsTrackerTransformers' has no attribute 'payment_frecuency'; 17740)
[2023-01-22T01:56:42.508+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-22T01:56:42.527+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
