[2023-01-22T04:24:09.621+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: debts_tracker_etl.upload_file_to_vendor_s3_location manual__2023-01-22T04:23:52.160309+00:00 [queued]>
[2023-01-22T04:24:09.636+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: debts_tracker_etl.upload_file_to_vendor_s3_location manual__2023-01-22T04:23:52.160309+00:00 [queued]>
[2023-01-22T04:24:09.638+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T04:24:09.639+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-01-22T04:24:09.640+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T04:24:09.658+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): upload_file_to_vendor_s3_location> on 2023-01-22 04:23:52.160309+00:00
[2023-01-22T04:24:09.668+0000] {standard_task_runner.py:55} INFO - Started process 4026 to run task
[2023-01-22T04:24:09.676+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'debts_tracker_etl', 'upload_file_to_vendor_s3_location', 'manual__2023-01-22T04:23:52.160309+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/debts_tracker_etl.py', '--cfg-path', '/tmp/tmpyc3olke8']
[2023-01-22T04:24:09.687+0000] {standard_task_runner.py:83} INFO - Job 78: Subtask upload_file_to_vendor_s3_location
[2023-01-22T04:24:09.792+0000] {task_command.py:388} INFO - Running <TaskInstance: debts_tracker_etl.upload_file_to_vendor_s3_location manual__2023-01-22T04:23:52.160309+00:00 [running]> on host 4b1c480b6ccb
[2023-01-22T04:24:09.886+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Tony Stark, Peter Parker
AIRFLOW_CTX_DAG_ID=debts_tracker_etl
AIRFLOW_CTX_TASK_ID=upload_file_to_vendor_s3_location
AIRFLOW_CTX_EXECUTION_DATE=2023-01-22T04:23:52.160309+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-22T04:23:52.160309+00:00
[2023-01-22T04:24:09.904+0000] {base.py:73} INFO - Using connection ID 'aws_conn' for task execution.
[2023-01-22T04:24:09.906+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='aws_conn', conn_type='aws') credentials retrieved from login and password.
[2023-01-22T04:24:11.118+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/boto3/s3/transfer.py", line 292, in upload_file
    future.result()
  File "/home/airflow/.local/lib/python3.8/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/home/airflow/.local/lib/python3.8/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/home/airflow/.local/lib/python3.8/site-packages/s3transfer/tasks.py", line 139, in __call__
    return self._execute_main(kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/s3transfer/tasks.py", line 162, in _execute_main
    return_value = self._main(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/s3transfer/upload.py", line 758, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/transformers/debts_tracker/debts_tracker_transformer.py", line 135, in upload_file_to_vendor_s3_folder
    s3_hook.load_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 99, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 70, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 646, in load_file
    client.upload_file(filename, bucket_name, key, ExtraArgs=extra_args, Config=self.transfer_config)
  File "/home/airflow/.local/lib/python3.8/site-packages/boto3/s3/inject.py", line 143, in upload_file
    return transfer.upload_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/boto3/s3/transfer.py", line 298, in upload_file
    raise S3UploadFailedError(
boto3.exceptions.S3UploadFailedError: Failed to upload /opt/***/encryted_files/2023-01-22/encrypt_debts_file.csv to ***ww/orders/encrypt_debts_file.csv: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
[2023-01-22T04:24:11.132+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=debts_tracker_etl, task_id=upload_file_to_vendor_s3_location, execution_date=20230122T042352, start_date=20230122T042409, end_date=20230122T042411
[2023-01-22T04:24:11.155+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 78 for task upload_file_to_vendor_s3_location (Failed to upload /opt/***/encryted_files/2023-01-22/encrypt_debts_file.csv to ***ww/orders/encrypt_debts_file.csv: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied; 4026)
[2023-01-22T04:24:11.183+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-22T04:24:11.207+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
