[2023-01-21T21:15:51.162+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: crypto_coins_etl.place_order manual__2023-01-21T21:15:37.414039+00:00 [queued]>
[2023-01-21T21:15:51.174+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: crypto_coins_etl.place_order manual__2023-01-21T21:15:37.414039+00:00 [queued]>
[2023-01-21T21:15:51.175+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T21:15:51.175+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-21T21:15:51.176+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T21:15:51.189+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): place_order> on 2023-01-21 21:15:37.414039+00:00
[2023-01-21T21:15:51.195+0000] {standard_task_runner.py:55} INFO - Started process 4997 to run task
[2023-01-21T21:15:51.200+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'crypto_coins_etl', 'place_order', 'manual__2023-01-21T21:15:37.414039+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/crypto_coins_etl.py', '--cfg-path', '/tmp/tmp_7lytutb']
[2023-01-21T21:15:51.211+0000] {standard_task_runner.py:83} INFO - Job 206: Subtask place_order
[2023-01-21T21:15:51.296+0000] {task_command.py:388} INFO - Running <TaskInstance: crypto_coins_etl.place_order manual__2023-01-21T21:15:37.414039+00:00 [running]> on host 6256f74551c5
[2023-01-21T21:15:51.368+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=crypto_coins_etl
AIRFLOW_CTX_TASK_ID=place_order
AIRFLOW_CTX_EXECUTION_DATE=2023-01-21T21:15:37.414039+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-21T21:15:37.414039+00:00
[2023-01-21T21:15:51.383+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/transformers/crypto/crypto_transformer.py", line 79, in place_order
    res = HttpServices.submit_order(coin)
TypeError: submit_order() missing 1 required positional argument: 'quantity'
[2023-01-21T21:15:51.395+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=crypto_coins_etl, task_id=place_order, execution_date=20230121T211537, start_date=20230121T211551, end_date=20230121T211551
[2023-01-21T21:15:51.407+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 206 for task place_order (submit_order() missing 1 required positional argument: 'quantity'; 4997)
[2023-01-21T21:15:51.456+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-21T21:15:51.475+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
