[2023-01-22T04:13:00.515+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: debts_tracker_etl.upload_file_to_vendor_s3_location manual__2023-01-22T04:12:51.865185+00:00 [queued]>
[2023-01-22T04:13:00.525+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: debts_tracker_etl.upload_file_to_vendor_s3_location manual__2023-01-22T04:12:51.865185+00:00 [queued]>
[2023-01-22T04:13:00.526+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T04:13:00.527+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-01-22T04:13:00.528+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T04:13:00.540+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): upload_file_to_vendor_s3_location> on 2023-01-22 04:12:51.865185+00:00
[2023-01-22T04:13:00.547+0000] {standard_task_runner.py:55} INFO - Started process 3222 to run task
[2023-01-22T04:13:00.551+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'debts_tracker_etl', 'upload_file_to_vendor_s3_location', 'manual__2023-01-22T04:12:51.865185+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/debts_tracker_etl.py', '--cfg-path', '/tmp/tmpcu27d0gx']
[2023-01-22T04:13:00.557+0000] {standard_task_runner.py:83} INFO - Job 47: Subtask upload_file_to_vendor_s3_location
[2023-01-22T04:13:00.649+0000] {task_command.py:388} INFO - Running <TaskInstance: debts_tracker_etl.upload_file_to_vendor_s3_location manual__2023-01-22T04:12:51.865185+00:00 [running]> on host 4b1c480b6ccb
[2023-01-22T04:13:00.731+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Tony Stark, Peter Parker
AIRFLOW_CTX_DAG_ID=debts_tracker_etl
AIRFLOW_CTX_TASK_ID=upload_file_to_vendor_s3_location
AIRFLOW_CTX_EXECUTION_DATE=2023-01-22T04:12:51.865185+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-22T04:12:51.865185+00:00
[2023-01-22T04:13:00.733+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/transformers/debts_tracker/debts_tracker_transformer.py", line 133, in upload_file_to_vendor_s3_folder
    source_file = kwargs['file_url']
KeyError: 'file_url'
[2023-01-22T04:13:00.745+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=debts_tracker_etl, task_id=upload_file_to_vendor_s3_location, execution_date=20230122T041251, start_date=20230122T041300, end_date=20230122T041300
[2023-01-22T04:13:00.757+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 47 for task upload_file_to_vendor_s3_location ('file_url'; 3222)
[2023-01-22T04:13:00.805+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-22T04:13:00.827+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
