[2023-01-22T03:28:45.088+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: debts_tracker_etl.create_encrypt_file manual__2023-01-22T03:28:30.524135+00:00 [queued]>
[2023-01-22T03:28:45.104+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: debts_tracker_etl.create_encrypt_file manual__2023-01-22T03:28:30.524135+00:00 [queued]>
[2023-01-22T03:28:45.105+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T03:28:45.106+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-01-22T03:28:45.107+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T03:28:45.126+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): create_encrypt_file> on 2023-01-22 03:28:30.524135+00:00
[2023-01-22T03:28:45.136+0000] {standard_task_runner.py:55} INFO - Started process 376 to run task
[2023-01-22T03:28:45.140+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'debts_tracker_etl', 'create_encrypt_file', 'manual__2023-01-22T03:28:30.524135+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/debts_tracker_etl.py', '--cfg-path', '/tmp/tmp81_i8nis']
[2023-01-22T03:28:45.144+0000] {standard_task_runner.py:83} INFO - Job 15: Subtask create_encrypt_file
[2023-01-22T03:28:45.246+0000] {task_command.py:388} INFO - Running <TaskInstance: debts_tracker_etl.create_encrypt_file manual__2023-01-22T03:28:30.524135+00:00 [running]> on host 4b1c480b6ccb
[2023-01-22T03:28:45.329+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Tony Stark, Peter Parker
AIRFLOW_CTX_DAG_ID=debts_tracker_etl
AIRFLOW_CTX_TASK_ID=create_encrypt_file
AIRFLOW_CTX_EXECUTION_DATE=2023-01-22T03:28:30.524135+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-22T03:28:30.524135+00:00
[2023-01-22T03:28:45.352+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/transformers/debts_tracker/debts_tracker_transformer.py", line 116, in encrypt_debts_data
    today_date = datetime.time.strftime("/%Y/%m/%d")
AttributeError: 'method_descriptor' object has no attribute 'strftime'
[2023-01-22T03:28:45.368+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=debts_tracker_etl, task_id=create_encrypt_file, execution_date=20230122T032830, start_date=20230122T032845, end_date=20230122T032845
[2023-01-22T03:28:45.388+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 15 for task create_encrypt_file ('method_descriptor' object has no attribute 'strftime'; 376)
[2023-01-22T03:28:45.436+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-22T03:28:45.458+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
