[2023-01-21T20:50:58.788+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: crypto_coins_etl.cal_avg_price_using_coin_history manual__2023-01-21T20:50:51.388968+00:00 [queued]>
[2023-01-21T20:50:58.803+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: crypto_coins_etl.cal_avg_price_using_coin_history manual__2023-01-21T20:50:51.388968+00:00 [queued]>
[2023-01-21T20:50:58.804+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T20:50:58.805+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-21T20:50:58.806+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T20:50:58.822+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): cal_avg_price_using_coin_history> on 2023-01-21 20:50:51.388968+00:00
[2023-01-21T20:50:58.829+0000] {standard_task_runner.py:55} INFO - Started process 3375 to run task
[2023-01-21T20:50:58.834+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'crypto_coins_etl', 'cal_avg_price_using_coin_history', 'manual__2023-01-21T20:50:51.388968+00:00', '--job-id', '185', '--raw', '--subdir', 'DAGS_FOLDER/crypto_coins_etl.py', '--cfg-path', '/tmp/tmpvr1c4gei']
[2023-01-21T20:50:58.838+0000] {standard_task_runner.py:83} INFO - Job 185: Subtask cal_avg_price_using_coin_history
[2023-01-21T20:50:58.931+0000] {task_command.py:388} INFO - Running <TaskInstance: crypto_coins_etl.cal_avg_price_using_coin_history manual__2023-01-21T20:50:51.388968+00:00 [running]> on host 6256f74551c5
[2023-01-21T20:50:59.019+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=crypto_coins_etl
AIRFLOW_CTX_TASK_ID=cal_avg_price_using_coin_history
AIRFLOW_CTX_EXECUTION_DATE=2023-01-21T20:50:51.388968+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-21T20:50:51.388968+00:00
[2023-01-21T20:50:59.034+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/transformers/crypto/crypto_transformer.py", line 67, in cal_avg_price
    for item in must_buy_coins:
TypeError: cal_avg_price() takes 2 positional arguments but 27 were given
[2023-01-21T20:50:59.045+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=crypto_coins_etl, task_id=cal_avg_price_using_coin_history, execution_date=20230121T205051, start_date=20230121T205058, end_date=20230121T205059
[2023-01-21T20:50:59.059+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 185 for task cal_avg_price_using_coin_history (cal_avg_price() takes 2 positional arguments but 27 were given; 3375)
[2023-01-21T20:50:59.089+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-21T20:50:59.110+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
